# Generated by Django 6.0.4 on 2026-04-08 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breaks', '0001_initial'),
        ('operations', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pauserequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pause_requests', to='operations.worksession'),
        ),
        migrations.AddField(
            model_name='pauserequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pause_requests', to='teams.team'),
        ),
        migrations.AddField(
            model_name='pauserequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pause_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pauserequest',
            name='pause_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pause_requests', to='breaks.pausetype'),
        ),
        migrations.AddConstraint(
            model_name='pauserequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='unique_pending_pause_request_per_user'),
        ),
        migrations.AddConstraint(
            model_name='pauserequest',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('status', 'approved')), fields=('user',), name='unique_active_pause_per_user'),
        ),
    ]
