# Generated by Django 6.0.4 on 2026-04-08 11:22

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauserequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pausetype',
            name='duration_minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pausetype',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
