# Generated by Django 6.0.4 on 2026-04-08 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breaks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('paused', 'Paused'), ('offline', 'Offline')], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pause_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_status_logs', to='breaks.pauserequest')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_logs', to='operations.worksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_status_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_work_session_per_user'),
        ),
        migrations.AddConstraint(
            model_name='workstatuslog',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='unique_open_work_status_log_per_user'),
        ),
    ]
